# Result checking for PANDAS and SPARK version

## Import necessary libraries

In [1]:
# Add current directory to Python path for imports
import os
import sys

# Add the parent directory (project root) to Python path so we can import from src
project_root = os.path.dirname(os.getcwd())
if project_root not in sys.path:
    sys.path.append(project_root)

In [2]:
import pandas as pd

---

## Load the datasets

In [3]:
RAW_PATH = os.path.join("..", "data", "raw", "bangkok_traffy.csv")
PANDAS_VER_PATH = os.path.join("..", "data", "processed", "cleansed_data.csv")
SPARK_VER_PATH = os.path.join("..", "data", "processed", "cleansed_data_spark.csv")

# Load the datasets
raw_df = pd.read_csv(RAW_PATH, engine="python")
pandas_df = pd.read_csv(PANDAS_VER_PATH, engine="python")
spark_df = pd.read_csv(SPARK_VER_PATH, engine="python")

columns = pandas_df.columns.tolist()
spark_df = spark_df.loc[:, columns]

raw_df.sort_values(by=raw_df.columns.tolist(), inplace=True)
pandas_df.sort_values(by=pandas_df.columns.tolist(), inplace=True)
spark_df.sort_values(by=spark_df.columns.tolist(), inplace=True)

raw_df.reset_index(drop=True, inplace=True)
pandas_df.reset_index(drop=True, inplace=True)
spark_df.reset_index(drop=True, inplace=True)

---

## Check for basic information

In [4]:
print("Raw DataFrame shape:", raw_df.shape)
print("Pandas DataFrame shape:", pandas_df.shape)
print("Spark DataFrame shape:", spark_df.shape)

print()

print(f"Check: {pandas_df.equals(spark_df)}")

Raw DataFrame shape: (787026, 16)
Pandas DataFrame shape: (697885, 17)
Spark DataFrame shape: (777156, 17)

Check: False

In [5]:
display(raw_df.head(3))
display(pandas_df.head(3))
display(spark_df.head(3))

,ticket_id,type,organization,comment,photo,photo_after,coords,address,subdistrict,district,province,timestamp,state,star,count_reopen,last_activity
0,2021-4D9Y98,{},"เขตลาดพร้าว,การไฟฟ้านครหลวง เขตนวลจันทร์",หน้าปากซอย ลาดพร้าววังหิน26,https://storage.googleapis.com/traffy_public_b...,https://storage.googleapis.com/traffy_public_b...,"100.59131,13.80910",17/73 17/73 ถ. ลาดพร้าววังหิน แขวงลาดพร้าว เขต...,ลาดพร้าว,ลาดพร้าว,กรุงเทพมหานคร,2021-12-13 05:53:36.861064+00,เสร็จสิ้น,NaN,0,2023-03-14 12:09:14.947437+00
1,2021-7K6QA3,{},"เขตประเวศ,ฝ่ายเทศกิจ เขตประเวศ",ระยะหลังๆ นี้ พบเจอรถสิบล้อขนดิน ใส่ยางบังโคลน...,https://storage.googleapis.com/traffy_public_b...,https://storage.googleapis.com/traffy_public_b...,"100.65617,13.72812",208/22 ถ. พัฒนาการ แขวง ประเวศ เขต ประเวศ กรุง...,ประเวศ,ประเวศ,กรุงเทพมหานคร,2021-12-21 23:03:58.450912+00,เสร็จสิ้น,2.0,0,2022-06-24 06:32:34.671236+00
2,2021-7U9RED,{},เขตดุสิต,ยังไม่มีหน่วยงานไหนมาดูแลครับ รถจะเชี่ยวหลายคน...,https://storage.googleapis.com/traffy_public_b...,https://storage.googleapis.com/traffy_public_b...,"100.50848,13.77832",627 ถนนสามเสน แขวง ดุสิต เขตดุสิต กรุงเทพมหานค...,ดุสิต,ดุสิต,กรุงเทพมหานคร,2021-12-17 08:46:02.610983+00,เสร็จสิ้น,5.0,0,2023-05-17 06:11:32.463984+00

,ticket_id,type,organization,comment,address,subdistrict,district,province,status,timestamp_date,timestamp_month,timestamp_year,last_activity_date,last_activity_month,last_activity_year,longitude,latitude
0,2021-4D9Y98,{},"เขตลาดพร้าว,การไฟฟ้านครหลวง เขตนวลจันทร์",หน้าปากซอย ลาดพร้าววังหิน26,17/73 17/73 ถ. ลาดพร้าววังหิน แขวงลาดพร้าว เขต...,ลาดพร้าว,ลาดพร้าว,กรุงเทพมหานคร,done,13,12,2021,14,3,2023,100.59131,13.80910
1,2021-7K6QA3,{},"เขตประเวศ,ฝ่ายเทศกิจ เขตประเวศ",ระยะหลังๆ นี้ พบเจอรถสิบล้อขนดิน ใส่ยางบังโคลน...,208/22 ถ. พัฒนาการ แขวง ประเวศ เขต ประเวศ กรุง...,ประเวศ,ประเวศ,กรุงเทพมหานคร,done,21,12,2021,24,6,2022,100.65617,13.72812
2,2021-7U9RED,{},เขตดุสิต,ยังไม่มีหน่วยงานไหนมาดูแลครับ รถจะเชี่ยวหลายคน...,627 ถนนสามเสน แขวง ดุสิต เขตดุสิต กรุงเทพมหานค...,ดุสิต,ดุสิต,กรุงเทพมหานคร,done,17,12,2021,17,5,2023,100.50848,13.77832

,ticket_id,type,organization,comment,address,subdistrict,district,province,status,timestamp_date,timestamp_month,timestamp_year,last_activity_date,last_activity_month,last_activity_year,longitude,latitude
0,2021-4D9Y98,{},"เขตลาดพร้าว,การไฟฟ้านครหลวง เขตนวลจันทร์",หน้าปากซอย ลาดพร้าววังหิน26,17/73 17/73 ถ. ลาดพร้าววังหิน แขวงลาดพร้าว เขต...,ลาดพร้าว,ลาดพร้าว,กรุงเทพมหานคร,done,13,12,2021,14,3,2023,13.80910,100.59131
1,2021-7K6QA3,{},"เขตประเวศ,ฝ่ายเทศกิจ เขตประเวศ",ระยะหลังๆ นี้ พบเจอรถสิบล้อขนดิน ใส่ยางบังโคลน...,208/22 ถ. พัฒนาการ แขวง ประเวศ เขต ประเวศ กรุง...,ประเวศ,ประเวศ,กรุงเทพมหานคร,done,22,12,2021,24,6,2022,13.72812,100.65617
2,2021-7U9RED,{},เขตดุสิต,ยังไม่มีหน่วยงานไหนมาดูแลครับ รถจะเชี่ยวหลายคน...,627 ถนนสามเสน แขวง ดุสิต เขตดุสิต กรุงเทพมหานค...,ดุสิต,ดุสิต,กรุงเทพมหานคร,done,17,12,2021,17,5,2023,13.77832,100.50848

---

## Check for PANDAS version reliability

In [6]:
df_raw_not_pandas = raw_df[~raw_df["ticket_id"].isin(pandas_df["ticket_id"])]

print("Rows in RAW but not in PANDAS:", df_raw_not_pandas.shape[0])

Rows in RAW but not in PANDAS: 89141

In [8]:
df_raw_not_pandas.head(3)

,ticket_id,type,organization,comment,photo,photo_after,coords,address,subdistrict,district,province,timestamp,state,star,count_reopen,last_activity
6,2021-9U2NJT,{น้ำท่วม},"เขตบางซื่อ,ฝ่ายโยธา เขตบางซื่อ",น้ำท่วม,https://storage.googleapis.com/traffy_public_b...,https://storage.googleapis.com/traffy_public_b...,"100.53099,13.81853",12/14 ถนน กรุงเทพ- นนทบุรี แขวง บางซื่อ เขตบาง...,NaN,NaN,กรุงเทพมหานคร,2021-10-14 10:45:27.713884+00,เสร็จสิ้น,NaN,0,2022-09-08 08:35:43.784519+00
11,2021-FYJTFP,{ความสะอาด},เขตบางซื่อ,ขยะเยอะ,https://storage.googleapis.com/traffy_public_b...,NaN,"100.53084,13.81865",12/14 ถนน กรุงเทพ- นนทบุรี แขวง บางซื่อ เขตบาง...,NaN,NaN,กรุงเทพมหานคร,2021-09-03 12:51:09.453003+00,เสร็จสิ้น,NaN,0,2022-06-04 15:34:14.609206+00
29,2022-32444C,{ต้นไม้},"เขตบางบอน,ฝ่ายรักษาความสะอาดฯ เขตบางบอน,ผอ.เขต...",ปากซอยเอกชัย133 มีการปลูกต้นไม้ใหญ่และปลูกไม้พ...,https://storage.googleapis.com/traffy_public_b...,https://storage.googleapis.com/traffy_public_b...,"100.37112,13.63782",4/11 ถ. เอกชัย แขวง บางบอน เขตบางบอน กรุงเทพมห...,บางบอนเหนือ,บางบอน,กรุงเทพมหานคร,2022-06-30 02:15:16.835639+00,เสร็จสิ้น,5.0,0,2022-06-30 08:24:10.868508+00

In [9]:
import geopandas as gpd

from src.pipelines import DistrictSubdistrictTransformer
from src.utils import load_geographic_data

dst = DistrictSubdistrictTransformer(
    district_column="DISTRICT_N",
    subdistrict_column="SUBDISTR_1",
    prefix_bonus=True,
)

raw_geo_df = load_geographic_data()
result_df = pd.DataFrame(dst.fit_transform(raw_geo_df))

bangkok_gdf = gpd.GeoDataFrame(result_df, crs="EPSG:4326")

bangkok_gdf.groupby(["DISTRICT_N", "SUBDISTR_1"]).size().reset_index(
    name="counts"
).sort_values(by="counts", ascending=False)

duplicates = bangkok_gdf[
    bangkok_gdf.duplicated(subset=["DISTRICT_N", "SUBDISTR_1"], keep=False)
]
duplicates = duplicates.sort_values(by=["DISTRICT_N", "SUBDISTR_1"])

if duplicates.empty:
    print("No duplicates found.")
else:
    display(duplicates[["DISTRICT_N", "SUBDISTR_1"]])

No duplicates found.

In [ ]:
df_raw_not_pandas_bangkok = df_raw_not_pandas[
    (
        (df_raw_not_pandas["province"] == "กรุงเทพมหานคร")
        & (~df_raw_not_pandas["district"].isnull())
        & (~df_raw_not_pandas["subdistrict"].isnull())
    )
]

['100.37112,13.63782',
 '100.53253,13.78341',
 '100.67046,13.71931',
 '100.62941,13.71001',
 '100.64153,13.73720',
 '100.59137,13.68052',
 '100.48439,13.68389',
 '100.70273,13.74892',
 '100.63997,13.89282',
 '100.62513,13.88621']

In [11]:
df_raw_not_pandas_bangkok.head(5)

,ticket_id,type,organization,comment,photo,photo_after,coords,address,subdistrict,district,province,timestamp,state,star,count_reopen,last_activity
29,2022-32444C,{ต้นไม้},"เขตบางบอน,ฝ่ายรักษาความสะอาดฯ เขตบางบอน,ผอ.เขต...",ปากซอยเอกชัย133 มีการปลูกต้นไม้ใหญ่และปลูกไม้พ...,https://storage.googleapis.com/traffy_public_b...,https://storage.googleapis.com/traffy_public_b...,"100.37112,13.63782",4/11 ถ. เอกชัย แขวง บางบอน เขตบางบอน กรุงเทพมห...,บางบอนเหนือ,บางบอน,กรุงเทพมหานคร,2022-06-30 02:15:16.835639+00,เสร็จสิ้น,5.0,0,2022-06-30 08:24:10.868508+00
34,2022-324BEV,{แสงสว่าง},"เขตพญาไท,การไฟฟ้านครหลวง เขตสามเสน,การไฟฟ้านคร...",ไฟฟ้าดับ บริเวณ ซอยเศรษฐศิริ2 ตรงข้ามสวัสดิการ...,https://storage.googleapis.com/traffy_public_b...,https://storage.googleapis.com/traffy_public_b...,"100.53253,13.78341",71 4 ซอย เศรษฐศิริ 2 แขวง สามเสนใน เขตพญาไท กร...,สามเสนใน,พญาไท,กรุงเทพมหานคร,2022-06-29 12:04:36.258997+00,เสร็จสิ้น,4.0,0,2023-04-06 09:07:49.129876+00
45,2022-326294,NaN,"เขตประเวศ,ฝ่ายรักษาความสะอาดฯ เขตประเวศ,ผอ.เขต...",ตัวอย่างการแจ้ง รบกวนมาเก็บขยะด้วยครับ,https://storage.googleapis.com/traffy_public_b...,https://storage.googleapis.com/traffy_public_b...,"100.67046,13.71931",PM9C+P5G ถ. อ่อนนุช แขวง ประเวศ เขต ประเวศ กรุ...,ประเวศ,ประเวศ,กรุงเทพมหานคร,2022-08-02 10:47:07.982349+00,เสร็จสิ้น,NaN,0,2022-08-03 11:01:51.650347+00
74,2022-328HZD,{ต้นไม้},"เขตสวนหลวง,ฝ่ายเทศกิจ เขตสวนหลวง,ผอ.เขตสวนหลวง...",ติดป้ายตามเสาไฟฟ้า ต้นไม้ข้างทาง,https://storage.googleapis.com/traffy_public_b...,https://storage.googleapis.com/traffy_public_b...,"100.62941,13.71001",571 ซอยอ่อนนุช 44 แขวงสวนหลวง เขตสวนหลวง กรุงเ...,สวนหลวง,สวนหลวง,กรุงเทพมหานคร,2022-10-18 23:52:56.043234+00,เสร็จสิ้น,5.0,0,2023-02-09 08:07:45.65469+00
86,2022-329KU6,{ถนน},"เขตสวนหลวง,การรถไฟฟ้าขนส่งมวลชนแห่งประเทศไทย (...",บริเวณที่รอรถเมย์ถนนศรีนครินทร์ ตรงแยกศรีนคริน...,https://storage.googleapis.com/traffy_public_b...,https://storage.googleapis.com/traffy_public_b...,"100.64153,13.73720",1 ถนน ศรีนครินทร์ แขวง สวนหลวง แขวงสวนหลวง กรุ...,สวนหลวง,สวนหลวง,กรุงเทพมหานคร,2022-10-09 09:43:22.388364+00,เสร็จสิ้น,NaN,0,2023-07-25 09:57:42.884684+00

---

## Get different

In [12]:
# Cast ticket_id to string for accurate comparison
pandas_df["ticket_id"] = pandas_df["ticket_id"].astype("str")
spark_df["ticket_id"] = spark_df["ticket_id"].astype("str")


# Get Columns
columns = pandas_df.columns.tolist()
columns_indicated = [col + "_x" if col != "ticket_id" else col for col in columns]

columns_mapping = dict(zip(columns_indicated, columns))


# Join and get differences
df_pandas_not_spark = (
    pandas_df.merge(
        spark_df, on="ticket_id", how="left", indicator=True, suffixes=("_x", "_y")
    )
    .query('_merge == "left_only"')
    .drop(columns=["_merge"])
)

df_spark_not_pandas = (
    spark_df.merge(
        pandas_df, on="ticket_id", how="left", indicator=True, suffixes=("_x", "_y")
    )
    .query('_merge == "left_only"')
    .drop(columns=["_merge"])
)


# Rename columns for clarity
df_pandas_not_spark = df_pandas_not_spark.loc[:, columns_indicated]
df_pandas_not_spark = df_pandas_not_spark.rename(columns=columns_mapping)

df_spark_not_pandas = df_spark_not_pandas.loc[:, columns_indicated]
df_spark_not_pandas = df_spark_not_pandas.rename(columns=columns_mapping)


# Output the number of different rows
print("Rows in Pandas but not in Spark:", df_pandas_not_spark.shape[0])
print("Rows in Spark but not in Pandas:", df_spark_not_pandas.shape[0])

Rows in Pandas but not in Spark: 1
Rows in Spark but not in Pandas: 79272

In [13]:
if df_pandas_not_spark.shape[0] > 0:
    display(df_pandas_not_spark.head(3))

if df_spark_not_pandas.shape[0] > 0:
    display(df_spark_not_pandas.head(3))

,ticket_id,type,organization,comment,address,subdistrict,district,province,status,timestamp_date,timestamp_month,timestamp_year,last_activity_date,last_activity_month,last_activity_year,longitude,latitude
617429,BNXWL2,"{ร้องเรียน,ความปลอดภัย,ถนน,คลอง,แสงสว่าง}","เขตหนองแขม,การไฟฟ้านครหลวง เขตบางขุนเทียน,การไ...",ปัญหา: พบดวงไฟฟ้าส่องสว่างสาธารณะดับชำรุด จำนว...,16 ถ. เลียบคลองภาษีเจริญฝั่งใต้ กรุงเทพมหานคร ...,หนองแขม,หนองแขม,อำนาจเจริญ,done,2,4,2024,11,7,2024,100.37328,13.68599

,ticket_id,type,organization,comment,address,subdistrict,district,province,status,timestamp_date,timestamp_month,timestamp_year,last_activity_date,last_activity_month,last_activity_year,longitude,latitude
27,2022-32444C,{ต้นไม้},"เขตบางบอน,ฝ่ายรักษาความสะอาดฯ เขตบางบอน,ผอ.เขต...",ปากซอยเอกชัย133 มีการปลูกต้นไม้ใหญ่และปลูกไม้พ...,4/11 ถ. เอกชัย แขวง บางบอน เขตบางบอน กรุงเทพมห...,บอนเหนือ,บางบอน,กรุงเทพมหานคร,done,30,6,2022,30,6,2022,13.63782,100.37112
32,2022-324BEV,{แสงสว่าง},"เขตพญาไท,การไฟฟ้านครหลวง เขตสามเสน,การไฟฟ้านคร...",ไฟฟ้าดับ บริเวณ ซอยเศรษฐศิริ2 ตรงข้ามสวัสดิการ...,71 4 ซอย เศรษฐศิริ 2 แขวง สามเสนใน เขตพญาไท กร...,สามเสนใน,พญาไท,กรุงเทพมหานคร,done,29,6,2022,6,4,2023,13.78341,100.53253
71,2022-328HZD,{ต้นไม้},"เขตสวนหลวง,ฝ่ายเทศกิจ เขตสวนหลวง,ผอ.เขตสวนหลวง...",ติดป้ายตามเสาไฟฟ้า ต้นไม้ข้างทาง,571 ซอยอ่อนนุช 44 แขวงสวนหลวง เขตสวนหลวง กรุงเ...,สวนหลวง,สวนหลวง,กรุงเทพมหานคร,done,19,10,2022,9,2,2023,13.71001,100.62941

In [14]:
# Get the raw data of the differing rows for further investigation

df_raw_pandas_not_spark = raw_df[
    raw_df["ticket_id"].isin(df_pandas_not_spark["ticket_id"])
]
df_raw_spark_not_pandas = raw_df[
    raw_df["ticket_id"].isin(df_spark_not_pandas["ticket_id"])
]

In [15]:
if df_raw_pandas_not_spark.shape[0] > 0:
    display(df_raw_pandas_not_spark.head(3))

if df_raw_spark_not_pandas.shape[0] > 0:
    display(df_raw_spark_not_pandas.head(3))

,ticket_id,type,organization,comment,photo,photo_after,coords,address,subdistrict,district,province,timestamp,state,star,count_reopen,last_activity
690023,BNXWL2,"{ร้องเรียน,ความปลอดภัย,ถนน,คลอง,แสงสว่าง}","เขตหนองแขม,การไฟฟ้านครหลวง เขตบางขุนเทียน,การไ...",ปัญหา: พบดวงไฟฟ้าส่องสว่างสาธารณะดับชำรุด จำนว...,https://storage.googleapis.com/traffy_public_b...,https://storage.googleapis.com/traffy_public_b...,"100.37328,13.68599",16 ถ. เลียบคลองภาษีเจริญฝั่งใต้ กรุงเทพมหานคร ...,หนองแขม,หนองแขม,จังหวัดอำนาจเจริญ,2024-04-02 09:06:01.427064+00,เสร็จสิ้น,NaN,0,2024-07-11 07:51:56.209689+00

,ticket_id,type,organization,comment,photo,photo_after,coords,address,subdistrict,district,province,timestamp,state,star,count_reopen,last_activity
29,2022-32444C,{ต้นไม้},"เขตบางบอน,ฝ่ายรักษาความสะอาดฯ เขตบางบอน,ผอ.เขต...",ปากซอยเอกชัย133 มีการปลูกต้นไม้ใหญ่และปลูกไม้พ...,https://storage.googleapis.com/traffy_public_b...,https://storage.googleapis.com/traffy_public_b...,"100.37112,13.63782",4/11 ถ. เอกชัย แขวง บางบอน เขตบางบอน กรุงเทพมห...,บางบอนเหนือ,บางบอน,กรุงเทพมหานคร,2022-06-30 02:15:16.835639+00,เสร็จสิ้น,5.0,0,2022-06-30 08:24:10.868508+00
34,2022-324BEV,{แสงสว่าง},"เขตพญาไท,การไฟฟ้านครหลวง เขตสามเสน,การไฟฟ้านคร...",ไฟฟ้าดับ บริเวณ ซอยเศรษฐศิริ2 ตรงข้ามสวัสดิการ...,https://storage.googleapis.com/traffy_public_b...,https://storage.googleapis.com/traffy_public_b...,"100.53253,13.78341",71 4 ซอย เศรษฐศิริ 2 แขวง สามเสนใน เขตพญาไท กร...,สามเสนใน,พญาไท,กรุงเทพมหานคร,2022-06-29 12:04:36.258997+00,เสร็จสิ้น,4.0,0,2023-04-06 09:07:49.129876+00
74,2022-328HZD,{ต้นไม้},"เขตสวนหลวง,ฝ่ายเทศกิจ เขตสวนหลวง,ผอ.เขตสวนหลวง...",ติดป้ายตามเสาไฟฟ้า ต้นไม้ข้างทาง,https://storage.googleapis.com/traffy_public_b...,https://storage.googleapis.com/traffy_public_b...,"100.62941,13.71001",571 ซอยอ่อนนุช 44 แขวงสวนหลวง เขตสวนหลวง กรุงเ...,สวนหลวง,สวนหลวง,กรุงเทพมหานคร,2022-10-18 23:52:56.043234+00,เสร็จสิ้น,5.0,0,2023-02-09 08:07:45.65469+00

---